/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    //"aws_project_region": "ap-northeast-1",
    //"aws_cognito_identity_pool_id": "ap-northeast-1:4607b5d7-0768-493d-a0c0-abd4a8620be0",
    //"aws_cognito_region": "ap-northeast-1",
    //"aws_user_pools_id": "ap-northeast-1_m7On6BAGI",
    //"aws_user_pools_web_client_id": "2d4cvpuvedlidluurmja416gmc",
    
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:665b9401-085a-40bf-88a2-58cff147772f",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_XEWOirZSs",
    "aws_user_pools_web_client_id": "9du0383j9sckuaoku1vm6md5s",
    
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
